export const frontendFacts = [
  "The first web browser, WorldWideWeb, was also a WYSIWYG HTML editor.",
  "JavaScript was created in just 10 days by Brendan Eich in 1995.",
  "The first version of CSS was proposed by Håkon Wium Lie while working at CERN in 1994.",
  "React was first deployed on Facebook's News Feed in 2011 and later open-sourced in 2013.",
  "The term 'AJAX' was coined in 2005, though the technology existed earlier.",
  "The `<div>` element was introduced with HTML 3.2 in 1997.",
  "Chrome's V8 JavaScript engine is written in C++ and is open source.",
  "The first version of jQuery was released in 2006 by John Resig.",
  "The CSS Box Model was first introduced in CSS1 specification in 1996.",
  "TypeScript was developed by Microsoft and released in 2012.",
  "The first responsive website was launched in 2001 by Audi.",
  "HTML5 became a W3C recommendation in 2014 after years of development.",
  "The first CSS framework, Blueprint, was released in 2007.",
  "Vue.js was created by Evan You after working on Angular at Google.",
  "The term 'Progressive Web Apps' was coined by Google in 2015.",
  "Flexbox was first introduced in 2009 but gained widespread support in 2015.",
  "CSS Grid was first proposed by Microsoft in 2011.",
  "The first CSS preprocessor, Sass, was released in 2006.",
  "The npm package manager was created in 2010.",
  "The first version of Bootstrap was released by Twitter in 2011.",
  "WebAssembly became a W3C recommendation in 2019.",
  "The first version of Chrome DevTools was released in 2008.",
  "The term 'Single Page Application' gained popularity around 2010.",
  "ES6 (ECMAScript 2015) introduced major features like arrow functions and promises.",
  "The first version of Node.js was released by Ryan Dahl in 2009.",
  "The first CSS-in-JS library, styled-components, was released in 2016.",
  "The first version of webpack was released in 2012.",
  "The Shadow DOM specification was first introduced in 2012.",
  "React Hooks were introduced in React 16.8 in 2019.",
  "The first version of Redux was released in 2015.",
  "The CSS 'calc()' function was introduced in CSS3.",
  "The first version of Babel (formerly 6to5) was released in 2014.",
  "SVG became a W3C recommendation in 2001.",
  "The first version of ESLint was released in 2013.",
  "The Web Components specifications were first introduced in 2011.",
  "The first version of Create React App was released in 2016.",
  "The CSS Variables (Custom Properties) specification was finalized in 2015.",
  "The first version of Prettier was released in 2017.",
  "The HTTP/2 protocol was standardized in 2015.",
  "The first version of Next.js was released in 2016.",
  "The first version of Vite was released in 2020.",
  "The term 'JAMstack' was coined by Mathias Biilmann in 2016.",
  "The first version of Tailwind CSS was released in 2017.",
  "The WebSocket protocol was standardized in 2011.",
  "The first version of React Native was released in 2015.",
  "The CSS 'aspect-ratio' property was introduced in 2021.",
  "The first version of Gatsby was released in 2015.",
  "The term 'Micro-frontends' was first coined in 2016.",
  "The first version of Svelte was released in 2016.",
  "The CSS Container Queries specification was introduced in 2021.",
];
